-- Esquema de autenticación y autorización.
--
-- Nombres de tablas y columnas en inglés por convención del proyecto. Los roles se guardan por su
-- nombre en mayúsculas, que es el mismo valor del enum RoleName del código.
--
-- Las tablas viven en el esquema `core`, el default de Hibernate (hibernate.default_schema=core).

create table core.roles (
    id     bigint generated by default as identity primary key,
    name   varchar(40) not null unique
);

create table core.users (
    id                  uuid primary key,
    username            varchar(120) not null unique,
    password_hash       varchar(120) not null,
    two_factor_enabled  boolean      not null default false,
    two_factor_secret   varchar(120),
    enabled             boolean      not null default true,
    created_at          timestamptz  not null default now()
);

create table core.user_roles (
    user_id uuid   not null references core.users (id) on delete cascade,
    role_id bigint not null references core.roles (id) on delete cascade,
    primary key (user_id, role_id)
);

create table core.refresh_tokens (
    id         uuid primary key,
    user_id    uuid        not null references core.users (id) on delete cascade,
    token_hash varchar(64) not null unique,
    expires_at timestamptz not null,
    revoked    boolean     not null default false,
    created_at timestamptz not null default now()
);

create index idx_refresh_tokens_user on core.refresh_tokens (user_id);